# Setup
title:               Portfolio
tagline:             'Jensen Hu'
description:         ![1517458762231.jpg](/images/1517458762231.jpg)
url:                 https://jensennhu.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jensen Hu
  url:               https://github.com/jensennhu
  email:             Jensennhu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: #G-B6K9SCFRJR
