# Setup
title:               Portfolio
tagline:             'Jensen Hu'
description:         ![headshot](/images/0.JPG)
url:                 https://jensennhu.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jensen Hu
  url:               https://github.com/jensennhu
  email:             Jensennhu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
